name: CI

on:
  pull_request:
    branches: [ main, dev ]

env:
  BUILD_TYPE: Release

jobs:
  ubuntu_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel 2

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest
      
    - name: Benchmark
      working-directory: ${{github.workspace}}/build
      run: ./benchmarks
      
  windows_test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel 2

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest
        
      - name: Benchmark
        working-directory: ${{github.workspace}}/build/Release
        run: .\benchmarks.exe
